# @file .evolution.yml
# @description Evolution configuration for AI Evolution Engine
# @author IT-Journey Team <team@it-journey.org>
# @created 2025-07-05
# @lastModified 2025-07-12
# @version 1.1
#
# @relatedIssues 
#   - #evolution-configuration: Core evolution settings and automation
#
# @relatedEvolutions
#   - v1.1: Daily automation settings and mature stage
#   - v1.0: Initial evolution configuration
#
# @dependencies
#   - YAML: configuration format
#   - AI Evolution Engine: configuration consumer
#
# @changelog
#   - 2025-07-12: Added standardized file header - ITJ
#   - Previous: Evolution configuration updates
#
# @usage Loaded by evolution engine for configuration settings
# @notes Central configuration for evolution behavior and automation
#

# 🌱 Evolution Configuration
version: 1.1
growth:
  stage: mature # Updated from sapling to reflect daily automation capability
  strategy: adaptive
  auto_evolve: true

# Daily automation settings
daily_evolution:
  enabled: true
  schedule: "0 3 * * *" # 3 AM UTC daily
  default_type: "consistency"
  default_intensity: "minimal"
  skip_if_recent_changes: false # Set to true to skip if commits in last 24h
  max_issues_threshold: 10 # Skip if more than this many issues detected

ai:
  provider: ${AI_PROVIDER:-openai}
  model: ${AI_MODEL:-gpt-4-turbo}
  temperature: 0.6

evolution:
  max_context_files: 50
  max_context_line_per_file: 1000
  require_tests_for_features: true
  preserve_core_logic: true
  
  # Evolution type configurations
  types:
    consistency:
      safe_mode: true
      focus_areas: ["formatting", "naming", "structure"]
    error_fixing:
      safe_mode: true
      focus_areas: ["bugs", "validation", "error_handling"]
    documentation:
      safe_mode: false
      focus_areas: ["accuracy", "completeness", "examples"]
    code_quality:
      safe_mode: false
      focus_areas: ["readability", "performance", "maintainability"]
    security_updates:
      safe_mode: true
      focus_areas: ["dependencies", "permissions", "validation"]

sustainability:
  track_growth_metrics: true
  optimize_for_maintainability: true
  share_seed_improvements: true

# Periodic AI Prompts Configuration
periodic_prompts:
  enabled: true
  base_path: "prompts/templates"
  
  # Weekly prompts
  weekly:
    - name: doc_harmonization
      schedule: "0 2 * * 1"  # Mondays at 2 AM UTC
      template: "doc_harmonization.md"
      priority: high
      safe_mode: true
    - name: security_scan
      schedule: "0 3 * * 3"  # Wednesdays at 3 AM UTC
      template: "security_scan.md"
      priority: critical
      safe_mode: true
    - name: changelog_versioning
      schedule: "0 4 * * 5"  # Fridays at 4 AM UTC
      template: "changelog_versioning.md"
      priority: medium
      safe_mode: true

  # Bi-weekly prompts
  biweekly:
    - name: test_enhancement
      schedule: "0 2 * * 2"  # Tuesdays at 2 AM UTC (every other week)
      template: "test_enhancement.md"
      priority: high
      safe_mode: false
      frequency: "*/2"  # Every 2 weeks

  # Monthly prompts
  monthly:
    - name: code_refactor
      schedule: "0 1 1 * *"  # 1st day of month at 1 AM UTC
      template: "code_refactor.md"
      priority: medium
      safe_mode: false
    - name: dependency_updates
      schedule: "0 2 15 * *"  # 15th day of month at 2 AM UTC
      template: "dependency_updates.md"
      priority: high
      safe_mode: true
    - name: performance_optimization
      schedule: "0 3 8 * *"  # 8th day of month at 3 AM UTC
      template: "performance_optimization.md"
      priority: medium
      safe_mode: false
    - name: workflow_optimization
      schedule: "0 4 22 * *"  # 22nd day of month at 4 AM UTC
      template: "workflow_optimization.md"
      priority: medium
      safe_mode: true
    - name: community_guidelines
      schedule: "0 5 28 * *"  # 28th day of month at 5 AM UTC
      template: "community_guidelines.md"
      priority: low
      safe_mode: false
    - name: prompt_refinement
      schedule: "0 6 30 * *"  # 30th day of month at 6 AM UTC
      template: "prompt_refinement.md"
      priority: high
      safe_mode: false

  # Configuration for periodic prompt execution
  execution:
    dry_run_first: true
    create_pr_for_changes: true
    auto_merge_safe_changes: false
    max_execution_time: "45m"
    failure_notification: true
    success_metrics_tracking: true
  
# Quality gates
quality_gates:
  require_tests_pass: true
  require_lint_pass: true
  max_evolution_time: "30m"
  rollback_on_failure: true
