# 🌱 Evolution Configuration
version: 1.0
growth:
  stage: germination
  strategy: adaptive
  auto_evolve: true
  
ai:
  provider: ${AI_PROVIDER:-openai}
  model: ${AI_MODEL:-gpt-4}
  temperature: 0.7
  
evolution:
  max_tokens_per_growth: 100000
  require_tests: true
  preserve_core: true
  
sustainability:
  track_growth: true
  optimize_resources: true
  share_seeds: true
