#!/usr/bin/env bash
#
# @file scripts/generate_seed.sh
# @description Generates the next .seed.md content for the AI Evolution Engine
# @author IT-Journey Team <team@it-journey.org>
# @created 2025-07-05
# @lastModified 2025-07-05
# @version 2.0.0
#
# @relatedIssues 
#   - Refactor scripts to be modular with well-structured library
#
# @relatedEvolutions
#   - v2.0.0: Complete modular refactor using new library system
#
# @dependencies
#   - bash: >=4.0
#   - src/lib/core/bootstrap.sh: Library bootstrap
#   - src/lib/evolution/seeds.sh: Seed management
#
# @changelog
#   - 2025-07-05: Refactored to use modular library system - ITJ
#
# @usage ./generate_seed.sh <cycle> <generation> <prompt> <growth_mode>
# @notes Generates evolved seed content for next iteration
#

set -euo pipefail

# Get script directory for relative imports
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Bootstrap the modular library system
source "$PROJECT_ROOT/src/lib/core/bootstrap.sh"
bootstrap_library

# Load required modules
require_module "core/logger"
require_module "evolution/seeds"
require_module "template/engine"

# Initialize logging
init_logger "logs" "generate-seed"

# Parse command line arguments
NEW_CYCLE=""
NEW_GENERATION=""
PROMPT=""
GROWTH_MODE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --cycle)
            NEW_CYCLE="$2"
            shift 2
            ;;
        --generation)
            NEW_GENERATION="$2"
            shift 2
            ;;
        --prompt)
            PROMPT="$2"
            shift 2
            ;;
        --growth-mode)
            GROWTH_MODE="$2"
            shift 2
            ;;
        *)
            # Handle positional arguments for backward compatibility
            if [[ -z "$NEW_CYCLE" ]]; then
                NEW_CYCLE="$1"
            elif [[ -z "$NEW_GENERATION" ]]; then
                NEW_GENERATION="$1"
            elif [[ -z "$PROMPT" ]]; then
                PROMPT="$1"
            elif [[ -z "$GROWTH_MODE" ]]; then
                GROWTH_MODE="$1"
            fi
            shift
            ;;
    esac
done

# Set defaults
NEW_CYCLE="${NEW_CYCLE:-$(date +%Y%m%d)}"
NEW_GENERATION="${NEW_GENERATION:-1}"
PROMPT="${PROMPT:-Standard evolution cycle}"
GROWTH_MODE="${GROWTH_MODE:-adaptive}"

log_info "Generating seed for cycle $NEW_CYCLE, generation $NEW_GENERATION"
log_info "Growth mode: $GROWTH_MODE"

# Use the modular seed generation system
if seeds_generate_content "$NEW_CYCLE" "$NEW_GENERATION" "$PROMPT" "$GROWTH_MODE"; then
    log_info "✅ Seed content generated successfully"
else
    log_error "❌ Failed to generate seed content"
    exit 1
fi
*🌱 Generated by AI Evolution Engine v0.2.0 Workflow*
*"From sapling to forest, one cycle at a time."*
EOF

log_success "Seed content generated successfully for cycle $NEW_CYCLE"
