#!/usr/bin/env bash
# scripts/create_pr.sh
# Usage: create_pr.sh RESPONSE_FILE PROMPT GROWTH_MODE

set -e

RESPONSE_FILE="$1"
PROMPT="$2"
GROWTH_MODE="$3"

BRANCH_NAME=$(jq -r .new_branch "$RESPONSE_FILE")
COMMIT_MSG=$(jq -r .commit_message "$RESPONSE_FILE")
NEXT_SEED_PREVIEW=$(jq -r .next_seed_content "$RESPONSE_FILE" | head -n 20)

PR_BODY=$(cat <<EOF_PR_BODY
## 🌱 AI-Driven Growth Cycle Completed

**Growth Mode:** "$GROWTH_MODE"
**Original Prompt:** "$PROMPT"

### 🌿 Summary of Changes in this Cycle:
This cycle focused on evolving the codebase based on the prompt. Key changes include:
- Updates to evolution-metrics.json.
- Modifications to README.md dynamic block.
- Other changes as per the AI plan (see commit details).

### 🌰 Next Generation Seed (.seed.md) Highlights:
The following .seed.md has been generated to guide the next evolution:

```markdown
$NEXT_SEED_PREVIEW
... (see .seed.md in branch for full content)
```

---
*Generated by AI Evolution Engine v0.2.0 Workflow 🌱*
*Commit: $COMMIT_MSG*
EOF_PR_BODY
)

gh pr create \
  --title "$COMMIT_MSG" \
  --body "$PR_BODY" \
  --base main \
  --head "$BRANCH_NAME"
