#!/usr/bin/env bash
# scripts/generate_seed.sh
# Generates the next .seed.md content for the AI Evolution Engine

set -euo pipefail

# Get script directory for relative imports
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Source modular libraries
source "$PROJECT_ROOT/src/lib/core/logger.sh"
source "$PROJECT_ROOT/src/lib/core/environment.sh"

# Initialize logging
init_logger "logs" "generate-seed"

# Validate input parameters
if [[ $# -lt 4 ]]; then
    log_error "Usage: $0 <new_cycle> <new_generation> <prompt> <growth_mode>"
    exit 1
fi

NEW_CYCLE="$1"
NEW_GENERATION="$2"
PROMPT="$3"
GROWTH_MODE="$4"

log_info "Generating seed for cycle $NEW_CYCLE, generation $NEW_GENERATION"
log_info "Growth mode: $GROWTH_MODE"

cat <<EOF
# 🌱 AI Evolution Engine - Evolved Seed (Candidate for v0.3.0) 🌱

This seed was generated after growth cycle **#$NEW_CYCLE**.
**Prompt for this cycle:** "$PROMPT"
**Growth Mode:** $GROWTH_MODE

## 🌿 Evolutionary Leap Summary

This cycle (simulated) focused on:
 - Incrementing growth cycle to $NEW_CYCLE and generation to $NEW_GENERATION.
 - Updating `evolution-metrics.json` with the latest statistics.
 - Modifying `README.md` to reflect these new metrics within the `AI-EVOLUTION-MARKER` block.

## 🧬 Proposed Enhancements for v0.3.0 (Next Evolution)

Based on the current trajectory, the next evolutionary step (v0.3.0) should focus on:

 1.  **True AI Integration (Conceptual):**
     - Abstract the AI call: Create a script/interface (e.g., `src/ai_interface.sh`) that this workflow calls. Initially, it can use this simulation logic, but can be swapped for a real LLM call.
     - Define a clear API for the AI: What inputs it needs, what outputs (JSON structure) it must provide.
 2.  **Smarter Context Collection:**
     - Prioritize files based on recent changes or importance tags.
     - Allow dynamic adjustment of `max_context_files` and `max_context_line_per_file` based on prompt complexity.
 3.  **Advanced README Updates:**
     - Instead of just metrics, allow AI to add sections to README for new features (still using markers).
 4.  **Modular Growth Actions:**
     - Define specific "growth action types" in the AI response (e.g., `create_file`, `modify_function`, `add_test`, `update_docs`) beyond simple file replacement.

## 🚀 Planting this Evolved Seed

To continue evolution towards v0.3.0:
 1.  Review and merge the Pull Request from this growth cycle.
 2.  This `.seed.md` file now contains the refined blueprint.
 3.  The next run of `ai_evolver.yml` will use the evolved codebase as its starting point.

---
*🌱 Generated by AI Evolution Engine v0.2.0 Workflow*
*"From sapling to forest, one cycle at a time."*
EOF

log_success "Seed content generated successfully for cycle $NEW_CYCLE"
